name: magentodev-app
recipe: lamp
config:
  config:
    database: config/custom-mysql.conf
    php: config/php.ini
  php: '8.1'
  composer_version: '2.2.12'
  via: apache:2.4
  webroot: ./public_html
  xdebug: false
  database: mysql:8.0
rabbitmq: 
  type: rabbitmq:3.9
  disk: 512
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  myelasticsearch:
    type: elasticsearch:7.16.0
  mynginx:
    type: nginx:1.18
  database:
    type: mysql:8.0
  appserver:                                                                                                                                                                                  
    build_as_root:                                                                                                                                                                            
      - apt-get update -y -q
      - docker-php-ext-install sockets
      - apt-get install -y libxslt1-dev
      - docker-php-ext-enable apcu
      - docker-php-ext-enable bcmath
      - docker-php-ext-enable bz2
      - docker-php-ext-enable calendar
      - docker-php-ext-enable exif
      - docker-php-ext-enable gd
      - docker-php-ext-enable gettext
      - docker-php-ext-enable imagick
      - docker-php-ext-enable imap
      - docker-php-ext-enable intl
      - docker-php-ext-enable ldap
      - docker-php-ext-enable memcached
      - docker-php-ext-enable mysqli
      - docker-php-ext-enable oauth
      - docker-php-ext-enable opcache
      - docker-php-ext-enable pcntl
      - docker-php-ext-enable pdo_mysql
      - docker-php-ext-enable pdo_pgsql
      - docker-php-ext-enable redis
      - docker-php-ext-enable soap
      - docker-php-ext-enable sodium
      - docker-php-ext-enable zip
      - docker-php-ext-install xsl 
      # - pecl install amqp
      
  # cache:
  #   type: redis:6.2
  pma:
    type: phpmyadmin
    hosts:
    - database
proxy:
  pma:
  - pma.magentodev.lndo.site
  mailhog:
    - mail.magentodev.lndo.site

